import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import BottomNav from "@/components/BottomNav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="pc-banner-wrapper">
          <div className="pc-banner-left">
            <iframe src="/ad_160x600.html" width={160} height={600} frameBorder="0" scrolling="no" style={{ border: 'none', overflow: 'hidden' }} />
          </div>
          {children}
          <div className="pc-banner-right">
            <iframe src="/ad_160x600.html" width={160} height={600} frameBorder="0" scrolling="no" style={{ border: 'none', overflow: 'hidden' }} />
          </div>
        </div>
        <BottomNav />
      </body>
    </html>
  );
}
