import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import BottomNav from "@/components/BottomNav";
import AdBanner from "@/components/AdBanner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="pc-banner-wrapper">
          <div className="pc-banner-left">
            <AdBanner width={160} height={600} adKey="50def04d16f8e9305d859a279a6d77d0" />
          </div>
          {children}
          <div className="pc-banner-right">
            <AdBanner width={160} height={600} adKey="50def04d16f8e9305d859a279a6d77d0" />
          </div>
        </div>
        <BottomNav />
      </body>
    </html>
  );
}
